### ISSUE TITLE
If I change the target to 2015 or 2017 in this repo inside tsconfig.json - i get a tonne of type errors

### ISSUE THREAD

**Issue by probosckie** [mike-north/ts-fundamentals-v3#419]
![image](https://user-images.githubusercontent.com/8050145/147754913-e4d6e671-e195-4bd2-afef-51927fd776a5.png)

As per the frontend masters code, im changing the target to 2015 / 2017 - and when i run yarn dev - i get a tonne of type errors 

![image](https://user-images.githubusercontent.com/8050145/147754959-d7a9e238-e578-4905-a405-0e3a42e1f131.png)

**Comment by probosckie** [comment]
@mike-north

**Comment by mike-north** [comment]
This is expected when switching from a language target that doesn't support modules, to one that does. The error message is self-explanatory enough imo (`"moduleResolution": "node"`)
